/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.java.stagebus.view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

import com.java.stagebus.controller.LinhaController;
import com.java.stagebus.model.LinhaModel;
import com.java.stagebus.model.UsuarioModel;

/**
 *
 * @author User
 */
public class Tela_Linha_Detalhes extends javax.swing.JFrame {
	private static UsuarioModel userModel;
	private LinhaModel line = new LinhaModel();
	private LinhaController lineController = new LinhaController();
    /**
     * Creates new form Tela_1
     */
    public Tela_Linha_Detalhes() {
    	userModel = Tela_1.getDataUser();
    	line = Tela_Linha_Geral.getLine();
        initComponents();
         getContentPane().setBackground(java.awt.Color.WHITE);
      
        setExtendedState(MAXIMIZED_BOTH);
        
        ImageIcon icon = new ImageIcon("src/main/resources/Images/btn_voltar.png");
		Image image = icon.getImage().getScaledInstance(jButtonVoltar.getWidth(), jButtonVoltar.getHeight(),
				Image.SCALE_SMOOTH);
		jButtonVoltar.setIcon(new ImageIcon(image));
		
		ImageIcon icon2;

		  if(userModel.isEd_lin()) {
	        	icon = new ImageIcon("src/main/resources/Images/btn_editar.png");
	        icon2 = new ImageIcon("src/main/resources/Images/btn_excluir.png");
	        }
	        else {
	        	icon2 = new ImageIcon("src/main/resources/Images/btn_excluir_bloq.png");
	        	 icon = new ImageIcon("src/main/resources/Images/btn_editar_bloq.png");
	        	 jButtonEditar.setEnabled(false);
	        	 jButtonExcluir.setEnabled(false);
	        }
	        
	        image = icon.getImage().getScaledInstance(jButtonEditar.getWidth(), jButtonEditar.getHeight(), Image.SCALE_SMOOTH);
	        jButtonEditar.setIcon(new ImageIcon(image));
	        
	        image = icon2.getImage().getScaledInstance(jButtonExcluir.getWidth(), jButtonExcluir.getHeight(), Image.SCALE_SMOOTH);
	        jButtonExcluir.setIcon(new ImageIcon(image));

       
        
       

  
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabelIda = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jLabelHorarios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaIdaValue = new javax.swing.JTextArea();
        jLabelVolta = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaVoltaValue = new javax.swing.JTextArea();
        jLabelDomingo = new javax.swing.JLabel();
        jLabelSegunda = new javax.swing.JLabel();
        jLabelTerça = new javax.swing.JLabel();
        jLabelQuarta = new javax.swing.JLabel();
        jLabelQuinta = new javax.swing.JLabel();
        jLabelSexta = new javax.swing.JLabel();
        jLabelSabado = new javax.swing.JLabel();
        jLabelDomingoValue = new javax.swing.JLabel();
        jLabelSegundaValue = new javax.swing.JLabel();
        jLabelTercaValue = new javax.swing.JLabel();
        jLabelQuartaValue = new javax.swing.JLabel();
        jLabelQuintaValue = new javax.swing.JLabel();
        jLabelSextaValue = new javax.swing.JLabel();
        jLabelSabadoValue = new javax.swing.JLabel();
        List<String> lineByDay = lineController.carByDay(line.getId());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabelNome.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(127, 127, 127));
        jLabelNome.setText(line.getLinha() + " - " + line.getNome());

        jButtonEditar.setBorder(null);
        jButtonEditar.setBorder(null);
		jButtonEditar.setBackground(Color.WHITE);
		jButtonEditar.setBorderPainted(false);
		jButtonEditar.setContentAreaFilled(false);
		jButtonEditar.setCursor(new Cursor(HAND_CURSOR));
		jButtonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonEditarMouseClicked(evt);
			}

		});

		jButtonExcluir.setBorder(null);
		jButtonExcluir.setBorderPainted(false);
		jButtonExcluir.setContentAreaFilled(false);
		jButtonExcluir.setCursor(new Cursor(HAND_CURSOR));
		jButtonExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonExcluirMouseClicked(evt);
			}

		});

		jButtonVoltar.setBorder(null);
		jButtonVoltar.setBorderPainted(false);
		jButtonVoltar.setContentAreaFilled(false);
		jButtonVoltar.setCursor(new Cursor(HAND_CURSOR));
		jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonVoltarMouseClicked(evt);
			}

		});

        jLabelIda.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelIda.setForeground(new java.awt.Color(68, 114, 196));
        jLabelIda.setText("Ida:");

       

        jLabelHorarios.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHorarios.setHorizontalAlignment(SwingConstants.CENTER);
        jLabelHorarios.setCursor(new Cursor(HAND_CURSOR));
        jLabelHorarios.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelHorarios.setForeground(new java.awt.Color(68, 114, 196));
        jLabelHorarios.setText("Informações detalhadas de horário.");
        jLabelHorarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHorariosMouseClicked(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        jTextAreaIdaValue.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaIdaValue.setEditable(false);
        jTextAreaIdaValue.setColumns(20);
        jTextAreaIdaValue.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jTextAreaIdaValue.setForeground(new java.awt.Color(127, 127, 127));
        jTextAreaIdaValue.setRows(5);
        jTextAreaIdaValue.setText(line.getIda());
        jTextAreaIdaValue.setBorder(null);
        jTextAreaIdaValue.setOpaque(false);
        jTextAreaIdaValue.setWrapStyleWord(true);
        jTextAreaIdaValue.setLineWrap(true);
        jScrollPane1.setViewportView(jTextAreaIdaValue);

        jLabelVolta.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelVolta.setForeground(new java.awt.Color(68, 114, 196));
        jLabelVolta.setText("Volta:");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        jTextAreaVoltaValue.setBackground(new java.awt.Color(255, 255, 255));
        jTextAreaVoltaValue.setEditable(false);
        jTextAreaVoltaValue.setColumns(20);
        jTextAreaVoltaValue.setFont(new java.awt.Font("Calibri", 3, 18)); // NOI18N
        jTextAreaVoltaValue.setForeground(new java.awt.Color(127, 127, 127));
        jTextAreaVoltaValue.setRows(5);
        jTextAreaVoltaValue.setText(line.getVolta());
        jTextAreaVoltaValue.setBorder(null);
        jTextAreaVoltaValue.setOpaque(false);
        jTextAreaVoltaValue.setWrapStyleWord(true);
        jTextAreaVoltaValue.setLineWrap(true);
        jScrollPane2.setViewportView(jTextAreaVoltaValue);

        jLabelDomingo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelDomingo.setForeground(new java.awt.Color(68, 114, 196));
        jLabelDomingo.setText("Domingo");
        jLabelDomingo.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelSegunda.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelSegunda.setForeground(new java.awt.Color(68, 114, 196));
        jLabelSegunda.setText("Segunda");
        jLabelSegunda.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelTerça.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelTerça.setForeground(new java.awt.Color(68, 114, 196));
        jLabelTerça.setText("Terça");
        jLabelTerça.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelQuarta.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelQuarta.setForeground(new java.awt.Color(68, 114, 196));
        jLabelQuarta.setText("Quarta");
        jLabelQuarta.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelQuinta.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelQuinta.setForeground(new java.awt.Color(68, 114, 196));
        jLabelQuinta.setText("Quinta");
        jLabelQuinta.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelSexta.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelSexta.setForeground(new java.awt.Color(68, 114, 196));
        jLabelSexta.setText("Sexta");
        jLabelSexta.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelSabado.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelSabado.setForeground(new java.awt.Color(68, 114, 196));
        jLabelSabado.setText("Sábado");
        jLabelSabado.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelDomingoValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelDomingoValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelDomingoValue.setText(lineByDay.get(0));
        jLabelDomingoValue.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelSegundaValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelSegundaValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelSegundaValue.setText(lineByDay.get(1));
        jLabelSegundaValue.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelTercaValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelTercaValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelTercaValue.setText(lineByDay.get(2));
        jLabelTercaValue.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelQuartaValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelQuartaValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelQuartaValue.setText(lineByDay.get(3));
        jLabelQuartaValue.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelQuintaValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelQuintaValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelQuintaValue.setText(lineByDay.get(4));
        jLabelQuintaValue.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelSextaValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelSextaValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelSextaValue.setText(lineByDay.get(5));
        jLabelSextaValue.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelSabadoValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelSabadoValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelSabadoValue.setText(lineByDay.get(6));
        jLabelSabadoValue.setHorizontalAlignment(SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelVolta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelIda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 521, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2))
                                .addGap(50, 50, 50))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDomingo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSegunda, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTerça, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelQuarta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelQuinta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSexta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSabado, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDomingoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSegundaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTercaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelQuartaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelQuintaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSextaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSabadoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelHorarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(93, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(jLabelVolta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelIda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelDomingo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabelSegunda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelTerça, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelQuarta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelQuinta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelSexta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelSabado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDomingoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelSegundaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelTercaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelQuartaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelQuintaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelSextaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelSabadoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(48, 48, 48)
                        .addComponent(jLabelHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    private void jButtonEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditarMouseClicked
        if(jButtonEditar.isEnabled()) {
        	new Tela_Linha_Editar().setVisible(true);
        	setVisible(false);
        }
    }//GEN-LAST:event_jButtonEditarMouseClicked

    private void jButtonExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonExcluirMouseClicked
    	 if(jButtonExcluir.isEnabled()) {
      	   Tela_Mensagem_Confirmacao.setRedirecionar("l");
             new Tela_Mensagem_Confirmacao().setVisible(true);
             setVisible(false);
         }
    }//GEN-LAST:event_jButtonExcluirMouseClicked

   

    private void jButtonVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseClicked
        new Tela_Linha_Geral().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonVoltarMouseClicked

   
    private void jLabelHorariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHorariosMouseClicked
       Tela_Linha_Horario.setIdLine(line.getId());
    	new Tela_Linha_Horario().setVisible(true);
       setVisible(false);
    }//GEN-LAST:event_jLabelHorariosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Linha_Detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Linha_Detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Linha_Detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Linha_Detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Linha_Detalhes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelDomingo;
    private javax.swing.JLabel jLabelDomingoValue;
    private javax.swing.JLabel jLabelHorarios;
    private javax.swing.JLabel jLabelIda;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelQuarta;
    private javax.swing.JLabel jLabelQuartaValue;
    private javax.swing.JLabel jLabelQuinta;
    private javax.swing.JLabel jLabelQuintaValue;
    private javax.swing.JLabel jLabelSabado;
    private javax.swing.JLabel jLabelSabadoValue;
    private javax.swing.JLabel jLabelSegunda;
    private javax.swing.JLabel jLabelSegundaValue;
    private javax.swing.JLabel jLabelSexta;
    private javax.swing.JLabel jLabelSextaValue;
    private javax.swing.JLabel jLabelTercaValue;
    private javax.swing.JLabel jLabelTerça;
    private javax.swing.JLabel jLabelVolta;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaIdaValue;
    private javax.swing.JTextArea jTextAreaVoltaValue;
    // End of variables declaration//GEN-END:variables
}
