/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.java.stagebus.view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.ImageIcon;

import com.java.stagebus.controller.HorarioController;
import com.java.stagebus.model.HorarioModel;
import com.java.stagebus.model.UsuarioModel;

/**
 *
 * @author User
 */
public class Tela_Horario_Geral extends javax.swing.JFrame {

	private HorarioController scheduleController = new HorarioController();
	private static UsuarioModel userModel;
	private static List<HorarioModel> schedule = new ArrayList<HorarioModel>();
	
	public static List<HorarioModel> getSchedule() {
		
		return schedule;
	}
    /**
     * Creates new form Tela_1
     */
    public Tela_Horario_Geral() {
    	userModel = Tela_1.getDataUser();
        initComponents();
         getContentPane().setBackground(java.awt.Color.WHITE);
      
        setExtendedState(MAXIMIZED_BOTH);
        
       
        ImageIcon icon = new ImageIcon("src/main/resources/Images/titulo_horario.png");
        Image image = icon.getImage().getScaledInstance(jLabelTitulo.getWidth(), jLabelTitulo.getHeight(), Image.SCALE_SMOOTH);
        jLabelTitulo.setIcon(new ImageIcon(image));
        
        icon = new ImageIcon("src/main/resources/Images/btn_home.png");
        image = icon.getImage().getScaledInstance(jButtonHome.getWidth(), jButtonHome.getHeight(), Image.SCALE_SMOOTH);
        jButtonHome.setIcon(new ImageIcon(image));
         // Dados da tabela
       
       
  
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jButtonNovo = new javax.swing.JButton();
        jButtonHome = new javax.swing.JButton();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jComboBoxObjeto = new javax.swing.JComboBox<>();
        jLabelFiltrarPor = new javax.swing.JLabel();
        jLabelObjeto = new javax.swing.JLabel();
        jButtonFiltrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabelTitulo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jButtonNovo.setCursor(new Cursor(HAND_CURSOR));
        jButtonNovo.setBackground(Color.WHITE);
        jButtonNovo.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jButtonNovo.setForeground(new java.awt.Color(127, 127, 127));
        jButtonNovo.setText("NOVO HORÁRIO");
        jButtonNovo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(127, 127, 127), 2, true));
        jButtonNovo.setEnabled(false);
        if(userModel.isCad_ed_hor()) {
        jButtonNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	jButtonNovoMouseClicked(evt);
            }
        });
        
        jButtonNovo.setEnabled(true);
        }
        	
        	

       
     

        jButtonHome.setBorder(null);
        jButtonHome.setCursor(new Cursor(HAND_CURSOR));
        jButtonHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	jButtonHomeMouseClicked(evt);
            }
        });

        jComboBoxTipo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Dia", "Carro", "Linha", "Funcionário", "Garagem" }));
        jComboBoxTipo.addItemListener(new ItemListener() {
            public void itemStateChanged(ItemEvent e) {
             if(e.getStateChange() == ItemEvent.SELECTED) {
            		if(jComboBoxTipo.getSelectedIndex() != 0) {
                    	jComboBoxObjeto.setEnabled(true);
                    	
                    	jComboBoxObjeto.setModel(new javax.swing.DefaultComboBoxModel<>(scheduleController.getFilterList(jComboBoxTipo.getSelectedIndex())));
                    	
                    	
                    }else {
                    	jComboBoxObjeto.setEnabled(false);
                    	jComboBoxObjeto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { ""}));
                    }
             }
            }
        });

        jComboBoxObjeto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jComboBoxObjeto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
        jComboBoxObjeto.setEnabled(false);

        jLabelFiltrarPor.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelFiltrarPor.setForeground(new java.awt.Color(127, 127, 127));
        jLabelFiltrarPor.setText("Filtrar por:");

        jLabelObjeto.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelObjeto.setForeground(new java.awt.Color(127, 127, 127));
        jLabelObjeto.setText("Objeto:");

        jButtonFiltrar.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonFiltrar.setForeground(new java.awt.Color(127, 127, 127));
        jButtonFiltrar.setText("Filtrar");
        jButtonFiltrar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(127, 127, 127), 2, true));
        jButtonFiltrar.addMouseListener(new java.awt.event.MouseAdapter() {
        	public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonFiltrarMouseClicked(evt);
            }
           
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 746, Short.MAX_VALUE)
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 517, Short.MAX_VALUE)
                        .addComponent(jButtonHome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelObjeto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.Alignment.LEADING, 0, 450, Short.MAX_VALUE)
                    .addComponent(jLabelFiltrarPor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBoxObjeto, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabelFiltrarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jLabelObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxObjeto, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(jButtonFiltrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void jButtonNovoMouseClicked(java.awt.event.MouseEvent evt) {                                         
       new Tela_Horario_Novo().setVisible(true);
       setVisible(false);
    }                                        

    private void jButtonFiltrarMouseClicked(java.awt.event.MouseEvent evt) {                                            
        if(jComboBoxObjeto.isEnabled()) {
        	schedule = scheduleController.search(jComboBoxTipo.getSelectedIndex(), jComboBoxObjeto.getSelectedItem().toString());
        	new Tela_Horario_Detalhes().setVisible(true);
        	setVisible(false);
        }
    } 
    
    private void jButtonHomeMouseClicked(java.awt.event.MouseEvent evt) {                                          
        new Tela_Inicial().setVisible(true);
        setVisible(false);
    } 
    
     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Horario_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Horario_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Horario_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Horario_Geral.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Horario_Geral().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonFiltrar;
    private javax.swing.JButton jButtonHome;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JComboBox<String> jComboBoxObjeto;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JLabel jLabelFiltrarPor;
    private javax.swing.JLabel jLabelObjeto;
    private javax.swing.JLabel jLabelTitulo;
    // End of variables declaration                   
}
