/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.java.stagebus.view;

import java.awt.Cursor;
import java.awt.Image;

import javax.swing.ImageIcon;

import com.java.stagebus.model.UsuarioModel;

/**
 *
 * @author User
 */
@SuppressWarnings("serial")
public class Tela_Inicial extends javax.swing.JFrame {

	private static UsuarioModel userModel;
	
	

	/**
	 * Creates new form Tela_1
	 */
	public Tela_Inicial() {
		userModel = Tela_1.getDataUser();
		initComponents();
		getContentPane().setBackground(java.awt.Color.WHITE);

		setExtendedState(MAXIMIZED_BOTH);

		ImageIcon icon = new ImageIcon("src//main//resources//Images//titulo.png");
		Image image = icon.getImage().getScaledInstance(jLabelTitulo.getWidth(), jLabelTitulo.getHeight(),
				Image.SCALE_SMOOTH);
		jLabelTitulo.setIcon(new ImageIcon(image));

		icon = new ImageIcon("src//main//resources//Images//btn_lista.png");
		image = icon.getImage().getScaledInstance(jButtonLista.getWidth(), jButtonLista.getHeight(),
				Image.SCALE_SMOOTH);
		jButtonLista.setIcon(new ImageIcon(image));

		int fixWidth = jButtonFuncionario.getWidth();
		int fixHeigth = jButtonFuncionario.getHeight();

		icon = new ImageIcon("src//main//resources//Images//btn_funcionario.png");
		image = icon.getImage().getScaledInstance(fixWidth, fixHeigth, Image.SCALE_SMOOTH);
		jButtonFuncionario.setIcon(new ImageIcon(image));

		icon = new ImageIcon("src//main//resources//Images//btn_linha.png");
		image = icon.getImage().getScaledInstance(jButtonLinha.getWidth(), jButtonLinha.getHeight(),
				Image.SCALE_SMOOTH);
		jButtonLinha.setIcon(new ImageIcon(image));

		icon = new ImageIcon("src//main//resources//Images//btn_garagem.png");
		image = icon.getImage().getScaledInstance(fixWidth, fixHeigth, Image.SCALE_SMOOTH);
		jButtonGaragem.setIcon(new ImageIcon(image));

		icon = new ImageIcon("src//main//resources//Images//btn_carro.png");
		image = icon.getImage().getScaledInstance(fixWidth, fixHeigth, Image.SCALE_SMOOTH);
		jButtonCarro.setIcon(new ImageIcon(image));

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabelTitulo = new javax.swing.JLabel();
		jButtonLista = new javax.swing.JButton();
		jButtonFuncionario = new javax.swing.JButton();
		jButtonLinha = new javax.swing.JButton();
		jButtonGaragem = new javax.swing.JButton();
		jButtonCarro = new javax.swing.JButton();
		jButtonTipoCarro = new javax.swing.JButton();
		jButtonUsuario = new javax.swing.JButton();
		jButtonRelatorio = new javax.swing.JButton();
		jButtonHorario = new javax.swing.JButton();
		  jLabelSair = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));

		jButtonLista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(68, 114, 196)));
		jButtonLista.setCursor(new Cursor(HAND_CURSOR));
		jButtonLista.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonListaMouseClicked(evt);
			}
		});

		jButtonFuncionario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 173, 71)));
		jButtonFuncionario.setCursor(new Cursor(HAND_CURSOR));
		jButtonFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonFuncionarioMouseClicked(evt);
			}
		});

		jButtonLinha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(237, 125, 49)));
		jButtonLinha.setCursor(new Cursor(HAND_CURSOR));
		jButtonLinha.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonLinhaMouseClicked(evt);
			}
		});

		jButtonGaragem.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 192, 0)));
		jButtonGaragem.setCursor(new Cursor(HAND_CURSOR));
		jButtonGaragem.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonGaragemMouseClicked(evt);
			}
		});

		jButtonCarro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 176, 240)));
		jButtonCarro.setCursor(new Cursor(HAND_CURSOR));
		jButtonCarro.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonCarroMouseClicked(evt);
			}
		});

		jButtonTipoCarro.setBackground(new java.awt.Color(68, 114, 196));
		jButtonTipoCarro.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
		jButtonTipoCarro.setForeground(new java.awt.Color(255, 255, 255));
		jButtonTipoCarro.setText("Tipo de carro");
		jButtonTipoCarro.setCursor(new Cursor(HAND_CURSOR));
		jButtonTipoCarro.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonTipoCarroMouseClicked(evt);
			}
		});

		jButtonUsuario.setBackground(new java.awt.Color(68, 114, 196));
		jButtonUsuario.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
		jButtonUsuario.setForeground(new java.awt.Color(255, 255, 255));
		jButtonUsuario.setText("Usuarios");
		jButtonUsuario.setCursor(new Cursor(HAND_CURSOR));
		jButtonUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonUsuarioMouseClicked(evt);
			}
		});

		jButtonRelatorio.setBackground(new java.awt.Color(68, 114, 196));
		jButtonRelatorio.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
		jButtonRelatorio.setForeground(new java.awt.Color(255, 255, 255));
		jButtonRelatorio.setText("Relatórios");
		jButtonRelatorio.setCursor(new Cursor(HAND_CURSOR));jButtonRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonRelatorioMouseClicked(evt);
			}
		});

		jButtonHorario.setBackground(new java.awt.Color(68, 114, 196));
		jButtonHorario.setCursor(new Cursor(HAND_CURSOR));
		jButtonHorario.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
		jButtonHorario.setForeground(new java.awt.Color(255, 255, 255));
		jButtonHorario.setText("Horário");
		jButtonHorario.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonHorarioMouseClicked(evt);
			}
		});

		jLabelSair.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
		jLabelSair.setCursor(new Cursor(HAND_CURSOR));
        jLabelSair.setForeground(new java.awt.Color(68, 114, 196));
        jLabelSair.setText("<html><u>Sair<u><html>");
        jLabelSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSairMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLista, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jButtonGaragem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonCarro, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                    .addComponent(jButtonLinha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonTipoCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jButtonRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonHorario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSair, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonLista, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonTipoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButtonLinha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonGaragem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jButtonRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jButtonHorario, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabelSair, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
	}// </editor-fold>//GEN-END:initComponents



	private void jButtonListaMouseClicked(java.awt.event.MouseEvent evt) {
		
		new Tela_Organizacao().setVisible(true);
		setVisible(false);
	}

	private void jButtonTipoCarroMouseClicked(java.awt.event.MouseEvent evt) {
		new Tela_TipoCarro_Geral().setVisible(true);
		setVisible(false);
	}

	private void jButtonUsuarioMouseClicked(java.awt.event.MouseEvent evt) {
		new Tela_Usuario_Geral().setVisible(true);
		setVisible(false);
	}

	private void jButtonHorarioMouseClicked(java.awt.event.MouseEvent evt) {
		new Tela_Horario_Geral().setVisible(true);
		setVisible(false);
	}

	private void jButtonGaragemMouseClicked(java.awt.event.MouseEvent evt) {
		new Tela_Garagem_Geral().setVisible(true);
		setVisible(false);
	}

	private void jButtonFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {
		new Tela_Funcionario_Geral().setVisible(true);
		setVisible(false);
	}

	private void jButtonCarroMouseClicked(java.awt.event.MouseEvent evt) {
		new Tela_Carro_Geral().setVisible(true);
		setVisible(false);
	}

	private void jButtonRelatorioMouseClicked(java.awt.event.MouseEvent evt) {
		new Tela_Relatorios().setVisible(true);
		setVisible(false);
	}

	private void jButtonLinhaMouseClicked(java.awt.event.MouseEvent evt) {
		new Tela_Linha_Geral().setVisible(true);
		setVisible(false);
	}
	
	 private void jLabelSairMouseClicked(java.awt.event.MouseEvent evt) {                                        
		 new Tela_1().setVisible(true);
			setVisible(false);
	    }       

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Tela_Inicial().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	 	private javax.swing.JButton jButtonRelatorio;
	    private javax.swing.JButton jButtonCarro;
	    private javax.swing.JButton jButtonFuncionario;
	    private javax.swing.JButton jButtonGaragem;
	    private javax.swing.JButton jButtonHorario;
	    private javax.swing.JButton jButtonLinha;
	    private javax.swing.JButton jButtonLista;
	    private javax.swing.JButton jButtonTipoCarro;
	    private javax.swing.JButton jButtonUsuario;
	    private javax.swing.JLabel jLabelSair;
	    private javax.swing.JLabel jLabelTitulo;
	// End of variables declaration//GEN-END:variables
}
