/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.java.stagebus.view;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Image;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableCellRenderer;

import com.java.stagebus.controller.HorarioController;
import com.java.stagebus.model.HorarioModel;
import com.java.stagebus.model.UsuarioModel;

/**
 *
 * @author User
 */
public class Tela_Linha_Horario extends javax.swing.JFrame {
	
	private HorarioController scheduleController = new HorarioController();
	private static int idLine;
	private List<HorarioModel> scheduleList;
	private UsuarioModel userModel;
	
	public static void setIdLine(int id) {
		
		idLine = id;
	}

    /**
     * Creates new form Tela_1
     */
    public Tela_Linha_Horario() {
    	userModel = Tela_1.getDataUser();
        initComponents();
         getContentPane().setBackground(java.awt.Color.WHITE);
      
        setExtendedState(MAXIMIZED_BOTH);
        ImageIcon icon = new ImageIcon("src/main/resources/Images/btn_voltar.png");
       Image image = icon.getImage().getScaledInstance(jButtonVoltar.getWidth(), jButtonVoltar.getHeight(), Image.SCALE_SMOOTH);
        jButtonVoltar.setIcon(new ImageIcon(image));
       
     
       
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	jScrollPane1 = new javax.swing.JScrollPane();
        jButtonVoltar = new javax.swing.JButton();
       

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jButtonVoltar.setBorder(null);
		jButtonVoltar.setBorderPainted(false);
		jButtonVoltar.setContentAreaFilled(false);
		jButtonVoltar.setCursor(new Cursor(HAND_CURSOR));
		jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonVoltarMouseClicked(evt);
			}

		});
		scheduleList = scheduleController.scheduleLineByDay(idLine);
		 Object[][] dados = scheduleController.generateScheduleCarList(scheduleList);
	

	        // Nomes das colunas
	        String[] colunas = {"Dia", "Hora", "Garagem", "Carro", "Motorista", "Cobrador"};

	        // Modelo da tabela
	        DefaultTableModel model = new DefaultTableModel(dados, colunas) {
	            @Override
	            public boolean isCellEditable(int row, int column) {
	                return false;  // Torna todas as células não editáveis
	            }
	        };

	        // Tabela com modelo personalizado
	        jTableHorarios = new JTable(model) {
	            @Override
	            public Component prepareRenderer(TableCellRenderer renderer, int row, int column) {
	                Component comp = super.prepareRenderer(renderer, row, column);

	                // Alterna a cor de fundo de linhas ímpares e pares
	                if (!isRowSelected(row)) {
	                    comp.setBackground(row % 2 == 0 ? new Color(207, 213, 234) : new Color(233, 235, 245));
	                }

	                return comp;
	            }
	        };
	        
	        jTableHorarios.setFont(new java.awt.Font("Calibri", 1, 18));
	        jTableHorarios.setForeground(new Color(68, 114, 196));
	        jTableHorarios.setRowHeight(30);
	        jTableHorarios.getColumnModel().getColumn(0).setPreferredWidth(200);
	    	jTableHorarios.getColumnModel().getColumn(1).setPreferredWidth(200);
	    	jTableHorarios.getColumnModel().getColumn(2).setPreferredWidth(300);
	    	jTableHorarios.getColumnModel().getColumn(3).setPreferredWidth(200);
	    	jTableHorarios.getColumnModel().getColumn(4).setPreferredWidth(500);
	    	jTableHorarios.getColumnModel().getColumn(5).setPreferredWidth(500);
	       
        jScrollPane1.setViewportView(jTableHorarios);
        JTableHeader header = jTableHorarios.getTableHeader();
        header.setBackground(new Color(102, 204, 0));

        

        //jTableUsuarios.getTableHeader().setForeground(Color.WHITE);
        jTableHorarios.getTableHeader().setBackground(new java.awt.Color(102, 204, 0));
        jTableHorarios.getTableHeader().setFont(new java.awt.Font("Calibri", 1, 18));
        jTableHorarios.setShowGrid(true);
        jTableHorarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTableHorarios.setSelectionBackground(new java.awt.Color(153, 255, 153));
        jTableHorarios.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.getViewport().setBackground(Color.WHITE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
                        .addGap(100, 100, 100))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
   
    private void jButtonVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVoltarMouseClicked
        new Tela_Linha_Detalhes().setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButtonVoltarMouseClicked

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Linha_Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Linha_Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Linha_Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Linha_Horario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Linha_Horario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHorarios;
    // End of variables declaration//GEN-END:variables
}
