/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.java.stagebus.view;

import java.awt.Image;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.util.ArrayList;
import java.util.List;

import javax.swing.ImageIcon;

import com.java.stagebus.controller.HorarioController;
import com.java.stagebus.model.UsuarioModel;

/**
 *
 * @author User
 */
public class Tela_Horario_Novo extends javax.swing.JFrame {
	private HorarioController scheduleController = new HorarioController();
	private static UsuarioModel userModel;

    /**
     * Creates new form Tela_Funcionario_Novo
     */
    public Tela_Horario_Novo() {
    	userModel = Tela_1.getDataUser();
		initComponents();
		getContentPane().setBackground(java.awt.Color.WHITE);

		setExtendedState(MAXIMIZED_BOTH);

		ImageIcon icon = new ImageIcon("src/main/resources/Images/titulo_novo_horario.png");
		Image image = icon.getImage().getScaledInstance(jLabelTitulo.getWidth(), jLabelTitulo.getHeight(),
				Image.SCALE_SMOOTH);
		jLabelTitulo.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();
        jTextFieldHoraValue = new javax.swing.JTextField();
        jLabelMotorista = new javax.swing.JLabel();
        jLabelCobrador = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMensagem = new javax.swing.JTextArea();
        jLabelDia = new javax.swing.JLabel();
        jLabelCarro = new javax.swing.JLabel();
        jLabelLinha = new javax.swing.JLabel();
        jTextFieldMinutoValue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxDia = new javax.swing.JComboBox<>();
        jComboBoxCarro = new javax.swing.JComboBox<>();
        jComboBoxLinha = new javax.swing.JComboBox<>();
        jComboBoxMotorista = new javax.swing.JComboBox<>();
        jComboBoxCobrador = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelHora.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelHora.setForeground(new java.awt.Color(68, 114, 196));
        jLabelHora.setText("Hora:");

        jTextFieldHoraValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldHoraValue.setForeground(new java.awt.Color(127, 127, 127));
        jTextFieldHoraValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 127, 127), 2));
        jTextFieldHoraValue.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
               
            }

            @Override
            public void focusLost(FocusEvent e) {
            	  if(jTextFieldHoraValue.getText().length()==1)
            	      jTextFieldHoraValue.setText("0" + jTextFieldHoraValue.getText().substring(0, 1));

            }
        });
        jTextFieldHoraValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldHoraValueKeyReleased(evt);
            }
        });

        jLabelMotorista.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelMotorista.setForeground(new java.awt.Color(68, 114, 196));
        jLabelMotorista.setText("Motorista:");

        jLabelCobrador.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelCobrador.setForeground(new java.awt.Color(68, 114, 196));
        jLabelCobrador.setText("Cobrador:");

        jButtonCancelar.setBackground(new java.awt.Color(68, 114, 196));
        jButtonCancelar.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setBorder(null);
        jButtonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelarMouseClicked(evt);
            }
        });

        jButtonSalvar.setBackground(new java.awt.Color(68, 114, 196));
        jButtonSalvar.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setBorder(null);
        jButtonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalvarMouseClicked(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        jTextAreaMensagem.setEditable(false);
        jTextAreaMensagem.setColumns(20);
        jTextAreaMensagem.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jTextAreaMensagem.setForeground(new java.awt.Color(255, 0, 0));
        jTextAreaMensagem.setLineWrap(true);
        jTextAreaMensagem.setRows(3);
        jTextAreaMensagem.setWrapStyleWord(true);
        jTextAreaMensagem.setBorder(null);
        jScrollPane1.setViewportView(jTextAreaMensagem);

        jLabelDia.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelDia.setForeground(new java.awt.Color(68, 114, 196));
        jLabelDia.setText("Dia:");

        jLabelCarro.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelCarro.setForeground(new java.awt.Color(68, 114, 196));
        jLabelCarro.setText("Carro:");

        jLabelLinha.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelLinha.setForeground(new java.awt.Color(68, 114, 196));
        jLabelLinha.setText("Linha:");

        jTextFieldMinutoValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldMinutoValue.setForeground(new java.awt.Color(127, 127, 127));
        jTextFieldMinutoValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 127, 127), 2));
        jTextFieldMinutoValue.addFocusListener(new FocusListener() {
            @Override
            public void focusGained(FocusEvent e) {
                
            }

            @Override
            public void focusLost(FocusEvent e) {
            	if(jTextFieldMinutoValue.getText().length()==1)
            	      jTextFieldMinutoValue.setText("0" + jTextFieldMinutoValue.getText().substring(0, 1));
            }
        });
        jTextFieldMinutoValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldMinutoValueKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(":");

        jComboBoxDia.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxDia.setForeground(new java.awt.Color(127, 127, 127));
        jComboBoxDia.setModel(new javax.swing.DefaultComboBoxModel<>(scheduleController.generateObjectList(scheduleController.listOfDay())));
        jComboBoxDia.setBorder(null);

        jComboBoxCarro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxCarro.setForeground(new java.awt.Color(127, 127, 127));
        jComboBoxCarro.setModel(new javax.swing.DefaultComboBoxModel<>(scheduleController.generateObjectList(scheduleController.listOfCar())));
        jComboBoxCarro.setBorder(null);

        jComboBoxLinha.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxLinha.setForeground(new java.awt.Color(127, 127, 127));
        jComboBoxLinha.setModel(new javax.swing.DefaultComboBoxModel<>(scheduleController.generateObjectList(scheduleController.listOfLine())));
        jComboBoxLinha.setBorder(null);
        
        List<String> aux = new ArrayList<String>();
        aux.add("0 - Nenhum");
        aux.addAll(scheduleController.listOfDriver());

        jComboBoxMotorista.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxMotorista.setForeground(new java.awt.Color(127, 127, 127));
        jComboBoxMotorista.setModel(new javax.swing.DefaultComboBoxModel<>(scheduleController.generateObjectList(aux)));
        jComboBoxMotorista.setBorder(null);
        
        aux = new ArrayList<String>();
        aux.add("0 - Nenhum");
        aux.addAll(scheduleController.listOfConductor());

        jComboBoxCobrador.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jComboBoxCobrador.setForeground(new java.awt.Color(127, 127, 127));
        jComboBoxCobrador.setModel(new javax.swing.DefaultComboBoxModel<>(scheduleController.generateObjectList(aux)));
        jComboBoxCobrador.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTextFieldHoraValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldMinutoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelHora, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxDia, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelMotorista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCarro, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(jComboBoxCarro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxMotorista, 0, 200, Short.MAX_VALUE))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxCobrador, 0, 200, Short.MAX_VALUE)
                            .addComponent(jLabelLinha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCobrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxLinha, 0, 200, Short.MAX_VALUE))))
                .addGap(200, 200, 200))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxDia, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxLinha, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHora, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHoraValue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMinutoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxCobrador, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>                        
                                                 

    private void jButtonSalvarMouseClicked(java.awt.event.MouseEvent evt) {                                           
    	if(scheduleController.insertSchedule(userModel.getId(), jComboBoxDia.getSelectedItem().toString(), jTextFieldHoraValue.getText() + ":" + jTextFieldMinutoValue.getText(), jComboBoxLinha.getSelectedItem().toString(), jComboBoxCarro.getSelectedItem().toString(),jComboBoxMotorista.getSelectedItem().toString() , jComboBoxCobrador.getSelectedItem().toString())) {
          	 Tela_Mensagem_Redirecionar.setRedirecionar("h");
          	  new Tela_Mensagem_Redirecionar().setVisible(true);
          	  setVisible(false);
            }else
          	  
          	  jTextAreaMensagem.setText(scheduleController.getMessage());
    }                                          

    private void jButtonCancelarMouseClicked(java.awt.event.MouseEvent evt) {                                             
    	  new Tela_Horario_Geral().setVisible(true);
          setVisible(false);
    }                                            
                                                                 

    private void jTextFieldHoraValueKeyReleased(java.awt.event.KeyEvent evt) {                                                
        if(jTextFieldHoraValue.getText().length()> 2)
        jTextFieldHoraValue.setText(jTextFieldHoraValue.getText().substring(0, 2));
        
        if(jTextFieldHoraValue.getText().length() > 1 && Integer.parseInt(jTextFieldHoraValue.getText().substring(0, 1)) > 2) 
            jTextFieldHoraValue.setText(jTextFieldHoraValue.getText().substring(0, 1));

           if(jTextFieldHoraValue.getText().length() > 1 && Integer.parseInt(jTextFieldHoraValue.getText().substring(0, 1)) == 2)
               if(Integer.valueOf(jTextFieldHoraValue.getText().substring(1, 2)) > 3) {
            jTextFieldHoraValue.setText(jTextFieldHoraValue.getText().substring(0, 1));
            }

    }                                               

    private void jTextFieldMinutoValueKeyReleased(java.awt.event.KeyEvent evt) {                                                               
        if(jTextFieldMinutoValue.getText().length()> 2)
        jTextFieldMinutoValue.setText(jTextFieldMinutoValue.getText().substring(0, 2));
        
        
        if(jTextFieldMinutoValue.getText().length() > 1 && Integer.parseInt(jTextFieldMinutoValue.getText().substring(0, 1)) > 5)
           
               
            jTextFieldMinutoValue.setText(jTextFieldMinutoValue.getText().substring(0, 1));

    }   
    
                                              

                                                


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Horario_Novo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Horario_Novo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Horario_Novo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Horario_Novo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Horario_Novo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxCarro;
    private javax.swing.JComboBox<String> jComboBoxCobrador;
    private javax.swing.JComboBox<String> jComboBoxDia;
    private javax.swing.JComboBox<String> jComboBoxLinha;
    private javax.swing.JComboBox<String> jComboBoxMotorista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCarro;
    private javax.swing.JLabel jLabelCobrador;
    private javax.swing.JLabel jLabelDia;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelLinha;
    private javax.swing.JLabel jLabelMotorista;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaMensagem;
    private javax.swing.JTextField jTextFieldMinutoValue;
    private javax.swing.JTextField jTextFieldHoraValue;
    // End of variables declaration                   
}
