package com.java.stagebus.view;

import java.awt.Image;

import javax.swing.ImageIcon;

import com.java.stagebus.controller.GaragemController;
import com.java.stagebus.model.UsuarioModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */


/**
 *
 * @author User
 */
public class Tela_Garagem_Nova extends javax.swing.JFrame {
	
	private GaragemController garageController = new GaragemController();
	private static UsuarioModel userModel;

    /**
     * Creates new form Tela_Funcionario_Novo
     */
    public Tela_Garagem_Nova() {
		userModel = Tela_1.getDataUser();
		initComponents();
		getContentPane().setBackground(java.awt.Color.WHITE);

		setExtendedState(MAXIMIZED_BOTH);

		ImageIcon icon = new ImageIcon("src/main/resources/Images/titulo_nova_garagem.png");
		Image image = icon.getImage().getScaledInstance(jLabelTitulo.getWidth(), jLabelTitulo.getHeight(),
				Image.SCALE_SMOOTH);
		jLabelTitulo.setIcon(new ImageIcon(image));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        jTextFieldCodigoValue = new javax.swing.JTextField();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaMensagem = new javax.swing.JTextArea();
        jLabelLocalizacao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaLocalizacaoValue = new javax.swing.JTextArea();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNomeValue = new javax.swing.JTextField();
        jLabelResponsavel = new javax.swing.JLabel();
        jTextFieldResponsavelValue = new javax.swing.JTextField();
        jLabelLargura = new javax.swing.JLabel();
        jLabelComprimento = new javax.swing.JLabel();
        jLabelAltura = new javax.swing.JLabel();
        jLabelMaximo = new javax.swing.JLabel();
        jTextFieldLarguraValue = new javax.swing.JTextField();
        jTextFieldComprimentoValue = new javax.swing.JTextField();
        jTextFieldAlturaValue = new javax.swing.JTextField();
        jTextFieldMaximoValue = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCodigo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelCodigo.setForeground(new java.awt.Color(68, 114, 196));
        jLabelCodigo.setText("Código:");

        jTextFieldCodigoValue.setEditable(false);
        jTextFieldCodigoValue.setBackground(new java.awt.Color(217, 217, 217));
        jTextFieldCodigoValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldCodigoValue.setForeground(new java.awt.Color(127, 127, 127));
        jTextFieldCodigoValue.setText(garageController.generateID()+"");
        jTextFieldCodigoValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 127, 127), 2));

        jButtonCancelar.setBackground(new java.awt.Color(68, 114, 196));
        jButtonCancelar.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonCancelar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setBorder(null);
        jButtonCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelarMouseClicked(evt);
            }
        });

        jButtonSalvar.setBackground(new java.awt.Color(68, 114, 196));
        jButtonSalvar.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jButtonSalvar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setBorder(null);
        jButtonSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalvarMouseClicked(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);

        jTextAreaMensagem.setEditable(false);
        jTextAreaMensagem.setColumns(20);
        jTextAreaMensagem.setFont(new java.awt.Font("Calibri", 3, 14)); // NOI18N
        jTextAreaMensagem.setForeground(new java.awt.Color(255, 0, 0));
        jTextAreaMensagem.setLineWrap(true);
        jTextAreaMensagem.setRows(3);
        jTextAreaMensagem.setWrapStyleWord(true);
        jTextAreaMensagem.setBorder(null);
        jScrollPane1.setViewportView(jTextAreaMensagem);

        jLabelLocalizacao.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelLocalizacao.setForeground(new java.awt.Color(68, 114, 196));
        jLabelLocalizacao.setText("Localização:");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(null);

        jTextAreaLocalizacaoValue.setColumns(20);
        jTextAreaLocalizacaoValue.setForeground(new java.awt.Color(127, 127, 127));
        jTextAreaLocalizacaoValue.setRows(5);
        jTextAreaLocalizacaoValue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(127, 127, 127), 2, true));
        jScrollPane2.setViewportView(jTextAreaLocalizacaoValue);

        jLabelNome.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(68, 114, 196));
        jLabelNome.setText("Nome:");

        jTextFieldNomeValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldNomeValue.setForeground(new java.awt.Color(127, 127, 127));
        jTextFieldNomeValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 127, 127), 2));

        jLabelResponsavel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelResponsavel.setForeground(new java.awt.Color(68, 114, 196));
        jLabelResponsavel.setText("Responsável:");

        jTextFieldResponsavelValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldResponsavelValue.setForeground(new java.awt.Color(127, 127, 127));
        jTextFieldResponsavelValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 127, 127), 2));

        jLabelLargura.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelLargura.setForeground(new java.awt.Color(68, 114, 196));
        jLabelLargura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelLargura.setText("Largura:");

        jLabelComprimento.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelComprimento.setForeground(new java.awt.Color(68, 114, 196));
        jLabelComprimento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelComprimento.setText("Comprimento:");

        jLabelAltura.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelAltura.setForeground(new java.awt.Color(68, 114, 196));
        jLabelAltura.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelAltura.setText("Altura:");

        jLabelMaximo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelMaximo.setForeground(new java.awt.Color(68, 114, 196));
        jLabelMaximo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabelMaximo.setText("Máx.:");

        jTextFieldLarguraValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldLarguraValue.setForeground(new java.awt.Color(127, 127, 127));
        jTextFieldLarguraValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 127, 127), 2));
        jTextFieldLarguraValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
            	jTextFieldLarguraKeyReleased(evt);
            }
        });

        jLabelComprimento.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelComprimento.setForeground(new java.awt.Color(68, 114, 196));
        jLabelComprimento.setText("Comprimento:");

        jTextFieldComprimentoValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldComprimentoValue.setForeground(new java.awt.Color(127, 127, 127));
        jTextFieldComprimentoValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 127, 127), 2));
        jTextFieldComprimentoValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
            	jTextFieldComprimentoKeyReleased(evt);
            }
        });
       

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(127, 127, 127));
        jLabel2.setText("m");

        jLabelAltura.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelAltura.setForeground(new java.awt.Color(68, 114, 196));
        jLabelAltura.setText("Altura:");

        jTextFieldAlturaValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldAlturaValue.setForeground(new java.awt.Color(127, 127, 127));
        jTextFieldAlturaValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 127, 127), 2));
     jTextFieldAlturaValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
            	jTextFieldAlturaKeyReleased(evt);
            }
        });

        jTextFieldMaximoValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jTextFieldMaximoValue.setForeground(new java.awt.Color(127, 127, 127));
        jTextFieldMaximoValue.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldMaximoValue.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 127, 127), 2));
        jTextFieldMaximoValue.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
            	jTextFieldMaximoKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(127, 127, 127));
        jLabel1.setText("m");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(127, 127, 127));
        jLabel2.setText("m");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(127, 127, 127));
        jLabel3.setText("m");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldCodigoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNomeValue)
                                    .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldResponsavelValue, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCodigo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelResponsavel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelLocalizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE))))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldComprimentoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldAlturaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldMaximoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldLarguraValue, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(174, 174, 174))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCodigoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLarguraValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldComprimentoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAlturaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelMaximo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMaximoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldNomeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2)
                            .addComponent(jTextFieldResponsavelValue))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>                        

    private void jButtonSalvarMouseClicked(java.awt.event.MouseEvent evt) {                                           
    	if(garageController.insertGarage(userModel.getId(), Integer.parseInt(jTextFieldCodigoValue.getText()), jTextFieldNomeValue.getText(), jTextFieldLarguraValue.getText(), jTextFieldComprimentoValue.getText(), jTextFieldAlturaValue.getText(), jTextFieldResponsavelValue.getText(), jTextAreaLocalizacaoValue.getText(), jTextFieldMaximoValue.getText())) {
       	 Tela_Mensagem_Redirecionar.setRedirecionar("g");
       	  new Tela_Mensagem_Redirecionar().setVisible(true);
       	  setVisible(false);
         }else
       	  
       	  jTextAreaMensagem.setText(garageController.getMessage());
    }                                          

    private void jButtonCancelarMouseClicked(java.awt.event.MouseEvent evt) {                                             
       new Tela_Garagem_Geral().setVisible(true);
       setVisible(false);
    } 
    
    private void jTextFieldLarguraKeyReleased(java.awt.event.KeyEvent evt) {                                          
        jTextFieldLarguraValue.setText(jTextFieldLarguraValue.getText().replaceAll("[^a-zA-Z0-9,.]", ""));
        jTextFieldLarguraValue.setText(jTextFieldLarguraValue.getText().replaceAll("[^\\d.,]", ""));
  	  
  }
    private void jTextFieldComprimentoKeyReleased(java.awt.event.KeyEvent evt) {                                          
    	jTextFieldComprimentoValue.setText(jTextFieldComprimentoValue.getText().replaceAll("[^a-zA-Z0-9,.]", ""));
    	jTextFieldComprimentoValue.setText(jTextFieldComprimentoValue.getText().replaceAll("[^\\d.,]", ""));
    	  
    }
    
    private void jTextFieldAlturaKeyReleased(java.awt.event.KeyEvent evt) {                                          
    	jTextFieldAlturaValue.setText(jTextFieldAlturaValue.getText().replaceAll("[^a-zA-Z0-9,.]", ""));
    	jTextFieldAlturaValue.setText(jTextFieldAlturaValue.getText().replaceAll("[^\\d.,]", ""));
    	  
    }
    private void jTextFieldMaximoKeyReleased(java.awt.event.KeyEvent evt) {                                          
    	jTextFieldMaximoValue.setText(jTextFieldMaximoValue.getText().replaceAll("[^a-zA-Z0-9]", ""));
    	jTextFieldMaximoValue.setText(jTextFieldMaximoValue.getText().replaceAll("[^\\d]", ""));
    	  
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Garagem_Nova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Garagem_Nova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Garagem_Nova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Garagem_Nova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Garagem_Nova().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAltura;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelComprimento;
    private javax.swing.JLabel jLabelLargura;
    private javax.swing.JLabel jLabelLocalizacao;
    private javax.swing.JLabel jLabelMaximo;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelResponsavel;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaLocalizacaoValue;
    private javax.swing.JTextArea jTextAreaMensagem;
    private javax.swing.JTextField jTextFieldAlturaValue;
    private javax.swing.JTextField jTextFieldCodigoValue;
    private javax.swing.JTextField jTextFieldComprimentoValue;
    private javax.swing.JTextField jTextFieldLarguraValue;
    private javax.swing.JTextField jTextFieldMaximoValue;
    private javax.swing.JTextField jTextFieldNomeValue;
    private javax.swing.JTextField jTextFieldResponsavelValue;
    // End of variables declaration                   
}

