/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.java.stagebus.view;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import javax.swing.ImageIcon;

import com.java.stagebus.controller.LoginController;
import com.java.stagebus.controller.UsuarioController;
import com.java.stagebus.main.StagebusApplication;
import com.java.stagebus.model.UsuarioModel;

/**
 *
 * @author User
 */
@SuppressWarnings("serial")
public class Tela_1 extends javax.swing.JFrame {
	

	private static UsuarioModel userModel = new UsuarioModel();

	
	public static UsuarioModel getDataUser() {
		
		return userModel;
	}

    /**
     * Creates new form Tela_1
     */
    public Tela_1() {
        initComponents();
         getContentPane().setBackground(java.awt.Color.WHITE);
      
        setExtendedState(MAXIMIZED_BOTH);
        
         jPanelImage.setLayout(new BorderLayout());
         jPanelImage.add(new ImagemJPanel("src//main//resources//Images//imagem_tela_inicial.png"), BorderLayout.CENTER);
         
         ImageIcon icon = new ImageIcon("src/main/resources/Images/logo.png");
         Image image = icon.getImage().getScaledInstance(jLabelLogo.getWidth(), jLabelLogo.getHeight(), Image.SCALE_SMOOTH);
         jLabelLogo.setIcon(new ImageIcon(image));
         
        
         
         
         
      
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {


    	  jLabelUsuario = new javax.swing.JLabel();
          jTextFieldUsuario = new javax.swing.JTextField();
          jLabelSenha = new javax.swing.JLabel();
          jPasswordFieldSenha = new javax.swing.JPasswordField();
          jPanelImage = new javax.swing.JPanel();
          jButtonEntrar = new javax.swing.JButton();
          jLabelMensagemErro = new javax.swing.JLabel();
          jLabelURL = new javax.swing.JLabel();
          jTextFieldURLValue = new javax.swing.JTextField();
          jLabelLogo = new javax.swing.JLabel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          setBackground(new java.awt.Color(255, 255, 255));

          jLabelUsuario.setBackground(new java.awt.Color(255, 255, 255));
          jLabelUsuario.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
          jLabelUsuario.setForeground(new java.awt.Color(127, 127, 127));
          jLabelUsuario.setText("Usuário");

          jTextFieldUsuario.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
          jTextFieldUsuario.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(127, 127, 127), 2, true));

          jLabelSenha.setBackground(new java.awt.Color(255, 255, 255));
          jLabelSenha.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
          jLabelSenha.setForeground(new java.awt.Color(127, 127, 127));
          jLabelSenha.setText("Senha");

          jPasswordFieldSenha.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
          jPasswordFieldSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(127, 127, 127), 2, true));
          
        

          jPanelImage.setBackground(new java.awt.Color(255, 0, 0));
          jPanelImage.setLayout(new java.awt.GridBagLayout());

          jButtonEntrar.setBackground(new java.awt.Color(68, 114, 196));
          jButtonEntrar.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
          jButtonEntrar.setForeground(new java.awt.Color(255, 255, 255));
          jButtonEntrar.setText("ENTRAR");
          jButtonEntrar.setBorder(null);
          jButtonEntrar.addActionListener(new ActionListener() {
              @Override
              public void actionPerformed(ActionEvent e) {
            	  
            	  StagebusApplication.setConexao(jTextFieldURLValue.getText());
            	  LoginController loginController = new LoginController();
            	  if(loginController.checkLogin(jPasswordFieldSenha.getText(), jTextFieldUsuario.getText())) {
            		  UsuarioController userController = new UsuarioController();
               	   userModel = userController.searchByUserName(jTextFieldUsuario.getText());
               	   new Tela_Inicial().setVisible(true);
               	   setVisible(false);
                  }
                  else {
               	   jLabelMensagemErro.setText("Os dados informados estão incorretos ou o usuário está inativo.");
               	   jTextFieldUsuario.setText("");
               	   jPasswordFieldSenha.setText("");
                  }
              }
          });
          
          
        

       

          jLabelMensagemErro.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
          jLabelMensagemErro.setForeground(new java.awt.Color(255, 0, 0));
          

          jLabelURL.setBackground(new java.awt.Color(255, 255, 255));
          jLabelURL.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
          jLabelURL.setForeground(new java.awt.Color(127, 127, 127));
          jLabelURL.setText("URL Empresa:");
          jTextFieldURLValue.addKeyListener(new KeyAdapter() {
              @Override
              public void keyPressed(KeyEvent e) {
                  if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                     jButtonEntrar.doClick();
                  }
              }
          });

          jTextFieldURLValue.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
          jTextFieldURLValue.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(127, 127, 127), 2, true));
     

          jLabelLogo.setBackground(new java.awt.Color(255, 255, 255));

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                  .addGap(100, 100, 100)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                      .addComponent(jButtonEntrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                      .addComponent(jLabelUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(jLabelSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(jPasswordFieldSenha)
                      .addComponent(jLabelMensagemErro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(jLabelURL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                      .addComponent(jTextFieldURLValue, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                      .addComponent(jLabelLogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addGap(100, 100, 100)
                  .addComponent(jPanelImage, javax.swing.GroupLayout.DEFAULT_SIZE, 874, Short.MAX_VALUE)
                  .addGap(0, 0, 0))
          );
          layout.setVerticalGroup(
              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
              .addGroup(layout.createSequentialGroup()
                  .addGap(0, 0, 0)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                      .addGroup(layout.createSequentialGroup()
                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                          .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addGap(50, 50, 50)
                          .addComponent(jLabelUsuario)
                          .addGap(10, 10, 10)
                          .addComponent(jTextFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addGap(30, 30, 30)
                          .addComponent(jLabelSenha)
                          .addGap(10, 10, 10)
                          .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addGap(30, 30, 30)
                          .addComponent(jLabelURL)
                          .addGap(10, 10, 10)
                          .addComponent(jTextFieldURLValue, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addGap(50, 50, 50)
                          .addComponent(jButtonEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addGap(20, 20, 20)
                          .addComponent(jLabelMensagemErro, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                          .addGap(0, 50, Short.MAX_VALUE))
                      .addComponent(jPanelImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                  .addGap(0, 0, 0))
          );

          pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
   
    
    
    
    
  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEntrar;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelMensagemErro;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelURL;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanelImage;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldURLValue;
    private javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
