/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.java.stagebus.view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;

import javax.swing.ImageIcon;

import com.java.stagebus.controller.UsuarioController;
import com.java.stagebus.model.UsuarioModel;

/**
 *
 * @author User
 */
public class Tela_Usuario_Detalhes extends javax.swing.JFrame {

	private UsuarioController userController = new UsuarioController();
	private static UsuarioModel userModel;
	private UsuarioModel dataUser;

	
	/**
	 * Creates new form Tela_1
	 */
	public Tela_Usuario_Detalhes() {
		userModel = Tela_1.getDataUser();
		dataUser = Tela_Usuario_Geral.getUser();
		initComponents();
		getContentPane().setBackground(java.awt.Color.WHITE);

		setExtendedState(MAXIMIZED_BOTH);

		ImageIcon icon = new ImageIcon("src/main/resources/Images/btn_voltar.png");
		Image image = icon.getImage().getScaledInstance(jButtonVoltar.getWidth(), jButtonVoltar.getHeight(),
				Image.SCALE_SMOOTH);
		jButtonVoltar.setIcon(new ImageIcon(image));

		if (userModel.isEd_user())
			icon = new ImageIcon("src/main/resources/Images/btn_editar.png");
		else {
			icon = new ImageIcon("src/main/resources/Images/btn_editar_bloq.png");
			jButtonEditar.setEnabled(false);
		}
		image = icon.getImage().getScaledInstance(jButtonEditar.getWidth(), jButtonEditar.getHeight(),
				Image.SCALE_SMOOTH);
		jButtonEditar.setIcon(new ImageIcon(image));

		if (userModel.isExc_user()  && userModel.getId() != dataUser.getId())
			icon = new ImageIcon("src/main/resources/Images/btn_excluir.png");
		else {
			icon = new ImageIcon("src/main/resources/Images/btn_excluir_bloq.png");
			jButtonExcluir.setEnabled(false);
		}
		image = icon.getImage().getScaledInstance(jButtonExcluir.getWidth(), jButtonExcluir.getHeight(),
				Image.SCALE_SMOOTH);
		jButtonExcluir.setIcon(new ImageIcon(image));

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabelNome = new javax.swing.JLabel();
		jLabelPermissoes = new javax.swing.JLabel();
		jLabelCad_User = new javax.swing.JLabel();
		jLabelCad_Car = new javax.swing.JLabel();
		jLabelCad_Gar = new javax.swing.JLabel();
		jLabelCad_Tipo_Car = new javax.swing.JLabel();
		jLabelCad_Lin = new javax.swing.JLabel();
		jLabelEd_User = new javax.swing.JLabel();
		jLabelEd_Car = new javax.swing.JLabel();
		jLabelEd_Gar = new javax.swing.JLabel();
		jLabelEd_Lin = new javax.swing.JLabel();
		jLabelEd_Tipo_Car = new javax.swing.JLabel();
		jLabelEm_Rel = new javax.swing.JLabel();
		jLabelCad_Ed_Hor = new javax.swing.JLabel();
		jLabelFun_User = new javax.swing.JLabel();
		jLabelAt_Des_User = new javax.swing.JLabel();
		jLabelEx_User = new javax.swing.JLabel();
		jButtonEditar = new javax.swing.JButton();
		jButtonExcluir = new javax.swing.JButton();
		jButtonVoltar = new javax.swing.JButton();
		jLabelCad_Fun = new javax.swing.JLabel();
		jLabelEd_Fun = new javax.swing.JLabel();
		jLabelStatus = new javax.swing.JLabel();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setBackground(new java.awt.Color(255, 255, 255));

		jLabelNome.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
		jLabelNome.setForeground(new java.awt.Color(127, 127, 127));
		jLabelNome.setText(dataUser.getNome() + " " + dataUser.getSobrenome());

		jLabelPermissoes.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
		jLabelPermissoes.setForeground(new java.awt.Color(68, 114, 196));
		jLabelPermissoes.setText("Permissões:");

		if (!dataUser.isCad_user())
			jLabelCad_User.setForeground(new Color(191, 191, 191));
		jLabelCad_User.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		jLabelCad_User.setText("Cadastrar usuário");

		if (!dataUser.isCad_car())
			jLabelCad_Car.setForeground(new Color(191, 191, 191));
		jLabelCad_Car.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		jLabelCad_Car.setText("Cadastrar carro");

		if (!dataUser.isCad_gar())
			jLabelCad_Gar.setForeground(new Color(191, 191, 191));
		jLabelCad_Gar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		jLabelCad_Gar.setText("Cadastrar garagem");

		if (!dataUser.isCad_tip_car())
			jLabelCad_Tipo_Car.setForeground(new Color(191, 191, 191));
		jLabelCad_Tipo_Car.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		jLabelCad_Tipo_Car.setText("Cadastrar tipo de carro");

		if (!dataUser.isCad_lin())
			jLabelCad_Lin.setForeground(new Color(191, 191, 191));
		jLabelCad_Lin.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		jLabelCad_Lin.setText("Cadastrar linha");

		if (!dataUser.isEd_user())
			jLabelEd_User.setForeground(new Color(191, 191, 191));
		jLabelEd_User.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		jLabelEd_User.setText("Editar usuário");

		if (!dataUser.isEd_car())
			jLabelEd_Car.setForeground(new Color(191, 191, 191));
		jLabelEd_Car.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		jLabelEd_Car.setText("Editar carro");

		if (!dataUser.isEd_gar())
			jLabelEd_Gar.setForeground(new Color(191, 191, 191));
		jLabelEd_Gar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		jLabelEd_Gar.setText("Editar garagem");

		if (!dataUser.isEd_lin())
			jLabelEd_Lin.setForeground(new Color(191, 191, 191));
		jLabelEd_Lin.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		jLabelEd_Lin.setText("Editar linha");

		if (!dataUser.isEd_tip_car())
			jLabelEd_Tipo_Car.setForeground(new Color(191, 191, 191));
		jLabelEd_Tipo_Car.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		jLabelEd_Tipo_Car.setText("Editar tipo de carro");

		if (!dataUser.isEm_rel())
			jLabelEm_Rel.setForeground(new Color(191, 191, 191));
		jLabelEm_Rel.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		jLabelEm_Rel.setText("Emitir relatórios");

		if (!dataUser.isCad_ed_hor())
			jLabelCad_Ed_Hor.setForeground(new Color(191, 191, 191));
		jLabelCad_Ed_Hor.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		jLabelCad_Ed_Hor.setText("Criar/editar horários");

		if (!dataUser.isPerm_user())
			jLabelFun_User.setForeground(new Color(191, 191, 191));
		jLabelFun_User.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		jLabelFun_User.setText("Atribuir função ao usuário");

		if (!dataUser.isAt_des_user())
			jLabelAt_Des_User.setForeground(new Color(191, 191, 191));
		jLabelAt_Des_User.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		jLabelAt_Des_User.setText("Ativar/desativar usuário");

		if (!dataUser.isExc_user())
			jLabelEx_User.setForeground(new Color(191, 191, 191));
		jLabelEx_User.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		jLabelEx_User.setText("Excluir usuário");

		if (!dataUser.isCad_fun())
			jLabelCad_Fun.setForeground(new Color(191, 191, 191));
		jLabelCad_Fun.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		jLabelCad_Fun.setText("Cadastrar funcionário");

		if (!dataUser.isEd_fun())
			jLabelEd_Fun.setForeground(new Color(191, 191, 191));
		jLabelEd_Fun.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
		jLabelEd_Fun.setText("Editar funcionário");

		if (!dataUser.isStatus())
			jLabelStatus.setText("Status: INATIVO");
		else
			jLabelStatus.setText("Status: ATIVO");
		jLabelStatus.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

		jButtonEditar.setBorder(null);
		jButtonEditar.setBackground(Color.WHITE);
		jButtonEditar.setBorderPainted(false);
		jButtonEditar.setContentAreaFilled(false);
		jButtonEditar.setCursor(new Cursor(HAND_CURSOR));
		jButtonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonEditarMouseClicked(evt);
			}

		});

		jButtonExcluir.setBorder(null);
		jButtonExcluir.setBorderPainted(false);
		jButtonExcluir.setContentAreaFilled(false);
		jButtonExcluir.setCursor(new Cursor(HAND_CURSOR));
		jButtonExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonExcluirMouseClicked(evt);
			}

		});

		jButtonVoltar.setBorder(null);
		jButtonVoltar.setBorderPainted(false);
		jButtonVoltar.setContentAreaFilled(false);
		jButtonVoltar.setCursor(new Cursor(HAND_CURSOR));
		jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButtonVoltarMouseClicked(evt);
			}

		});

		  javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
	        getContentPane().setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addGap(100, 100, 100)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(0, 0, Short.MAX_VALUE))
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(jLabelPermissoes, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                            .addComponent(jLabelNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                            .addGroup(layout.createSequentialGroup()
	                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                        .addComponent(jLabelCad_Tipo_Car, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                        .addComponent(jLabelCad_Lin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                        .addComponent(jLabelCad_Gar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                        .addComponent(jLabelCad_Car, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                        .addComponent(jLabelCad_User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
	                                    .addComponent(jLabelCad_Fun, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
	                                .addGap(50, 50, 50)
	                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addComponent(jLabelEd_Fun, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
	                                    .addComponent(jLabelEd_Tipo_Car, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
	                                    .addComponent(jLabelEd_Lin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(jLabelEd_Gar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(jLabelEd_Car, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(jLabelEd_User, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(layout.createSequentialGroup()
	                                .addGap(50, 50, 50)
	                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                                    .addComponent(jLabelEx_User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(jLabelAt_Des_User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(jLabelFun_User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(jLabelCad_Ed_Hor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(jLabelEm_Rel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                                    .addComponent(jLabelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
	                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
	                                .addGap(18, 18, Short.MAX_VALUE)
	                                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addGap(18, 18, 18)
	                                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                        .addGap(50, 50, 50))))
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addGroup(layout.createSequentialGroup()
	                .addContainerGap(66, Short.MAX_VALUE)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
	                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(jLabelPermissoes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(18, 18, 18)
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addGroup(layout.createSequentialGroup()
	                                .addComponent(jLabelCad_User, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(jLabelCad_Car, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(jLabelCad_Gar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(jLabelCad_Lin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(jLabelCad_Tipo_Car, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
	                            .addGroup(layout.createSequentialGroup()
	                                .addComponent(jLabelEd_User, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(jLabelEd_Car, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(jLabelEd_Gar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(jLabelEd_Lin, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                                .addComponent(jLabelEd_Tipo_Car, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(jLabelEm_Rel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(jLabelCad_Ed_Hor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(jLabelFun_User, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(jLabelAt_Des_User, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                        .addComponent(jLabelEx_User, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
	                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
	                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                    .addGroup(layout.createSequentialGroup()
	                        .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addGap(100, 158, Short.MAX_VALUE))
	                    .addGroup(layout.createSequentialGroup()
	                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	                            .addComponent(jLabelCad_Fun, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
	                            .addComponent(jLabelEd_Fun, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
	                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
	                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
	                        .addContainerGap(83, Short.MAX_VALUE))))
	        );

	        pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButtonEditarMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButtonEditarMouseClicked
		if(jButtonEditar.isEnabled()) {
			new Tela_Usuario_Editar().setVisible(true);
			setVisible(false);
		}
	}// GEN-LAST:event_jButtonEditarMouseClicked

	private void jButtonExcluirMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButtonExcluirMouseClicked
		 if(jButtonExcluir.isEnabled()) {
	    	   Tela_Mensagem_Confirmacao.setRedirecionar("u");
	           new Tela_Mensagem_Confirmacao().setVisible(true);
	           setVisible(false);
	       }
	}// GEN-LAST:event_jButtonExcluirMouseClicked

	private void jButtonVoltarMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jButtonVoltarMouseClicked
		new Tela_Usuario_Geral().setVisible(true);
		setVisible(false);
	}// GEN-LAST:event_jButtonVoltarMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Tela_Usuario_Detalhes.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Tela_Usuario_Detalhes.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Tela_Usuario_Detalhes.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Tela_Usuario_Detalhes.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Tela_Usuario_Detalhes().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButtonEditar;
	private javax.swing.JButton jButtonExcluir;
	private javax.swing.JButton jButtonVoltar;
	private javax.swing.JLabel jLabelAt_Des_User;
	private javax.swing.JLabel jLabelCad_Car;
	private javax.swing.JLabel jLabelCad_Ed_Hor;
	private javax.swing.JLabel jLabelCad_Fun;
	private javax.swing.JLabel jLabelCad_Gar;
	private javax.swing.JLabel jLabelCad_Lin;
	private javax.swing.JLabel jLabelCad_Tipo_Car;
	private javax.swing.JLabel jLabelCad_User;
	private javax.swing.JLabel jLabelEd_Car;
	private javax.swing.JLabel jLabelEd_Fun;
	private javax.swing.JLabel jLabelEd_Gar;
	private javax.swing.JLabel jLabelEd_Lin;
	private javax.swing.JLabel jLabelEd_Tipo_Car;
	private javax.swing.JLabel jLabelEd_User;
	private javax.swing.JLabel jLabelEm_Rel;
	private javax.swing.JLabel jLabelEx_User;
	private javax.swing.JLabel jLabelFun_User;
	private javax.swing.JLabel jLabelNome;
	private javax.swing.JLabel jLabelPermissoes;
	private javax.swing.JLabel jLabelStatus;
	// End of variables declaration//GEN-END:variables
}
