package com.java.stagebus.view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.SwingConstants;

import com.java.stagebus.controller.CarroController;
import com.java.stagebus.model.CarroModel;
import com.java.stagebus.model.UsuarioModel;

/**
 *
 * @author User
 */
public class Tela_Carro_Detalhes extends javax.swing.JFrame {
	private static UsuarioModel userModel;
	private static CarroModel car = new CarroModel();
	private CarroController carController = new CarroController();
	
	

    /**
     * Creates new form Tela_1
     */
    public Tela_Carro_Detalhes() {
    	userModel = Tela_1.getDataUser();
    	car = Tela_Carro_Geral.getCar();
        initComponents();
         getContentPane().setBackground(java.awt.Color.WHITE);
      
        setExtendedState(MAXIMIZED_BOTH);
        
       
        ImageIcon icon = new ImageIcon("src/main/resources/Images/imagem_carro.png");
        Image image = icon.getImage().getScaledInstance(jLabelImagem.getWidth(), jLabelImagem.getHeight(), Image.SCALE_SMOOTH);
        jLabelImagem.setIcon(new ImageIcon(image));
        
       
        icon = new ImageIcon("src/main/resources/Images/btn_voltar.png");
        image = icon.getImage().getScaledInstance(jButtonVoltar.getWidth(), jButtonVoltar.getHeight(), Image.SCALE_SMOOTH);
        jButtonVoltar.setIcon(new ImageIcon(image));
        
        ImageIcon icon2;
       
     
        	
        
        
        if(userModel.isEd_car()) {
        	icon = new ImageIcon("src/main/resources/Images/btn_editar.png");
        icon2 = new ImageIcon("src/main/resources/Images/btn_excluir.png");
        }
        else {
        	icon2 = new ImageIcon("src/main/resources/Images/btn_excluir_bloq.png");
        	 icon = new ImageIcon("src/main/resources/Images/btn_editar_bloq.png");
        	 jButtonEditar.setEnabled(false);
        	 jButtonExcluir.setEnabled(false);
        }
        
        image = icon.getImage().getScaledInstance(jButtonEditar.getWidth(), jButtonEditar.getHeight(), Image.SCALE_SMOOTH);
        jButtonEditar.setIcon(new ImageIcon(image));
        
        image = icon2.getImage().getScaledInstance(jButtonExcluir.getWidth(), jButtonExcluir.getHeight(), Image.SCALE_SMOOTH);
        jButtonExcluir.setIcon(new ImageIcon(image));

       

  
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabelHorarios = new javax.swing.JLabel();
        jLabelDomingo = new javax.swing.JLabel();
        jLabelSegunda = new javax.swing.JLabel();
        jLabelTerça = new javax.swing.JLabel();
        jLabelQuarta = new javax.swing.JLabel();
        jLabelQuinta = new javax.swing.JLabel();
        jLabelSexta = new javax.swing.JLabel();
        jLabelSabado = new javax.swing.JLabel();
        jLabelDomingoValue = new javax.swing.JLabel();
        jLabelSegundaValue = new javax.swing.JLabel();
        jLabelTercaValue = new javax.swing.JLabel();
        jLabelQuartaValue = new javax.swing.JLabel();
        jLabelQuintaValue = new javax.swing.JLabel();
        jLabelSextaValue = new javax.swing.JLabel();
        jLabelSabadoValue = new javax.swing.JLabel();
        jLabelImagem = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelTipoValue = new javax.swing.JLabel();
        jLabelGaragem = new javax.swing.JLabel();
        jLabelGaragemValue = new javax.swing.JLabel();
        jLabelPlaca = new javax.swing.JLabel();
        jLabelPlacaValue = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jLabelStatusValue = new javax.swing.JLabel();
        List<String> carByDay = carController.lineByDay(car.getNumero());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabelNome.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(127, 127, 127));
        jLabelNome.setText(car.getNumero() + " - " + car.getNome());

        jButtonEditar.setBorder(null);
      		jButtonEditar.setBackground(Color.WHITE);
      		jButtonEditar.setBorderPainted(false);
      		jButtonEditar.setContentAreaFilled(false);
      		jButtonEditar.setCursor(new Cursor(HAND_CURSOR));
      		jButtonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
      			public void mouseClicked(java.awt.event.MouseEvent evt) {
      				jButtonEditarMouseClicked(evt);
      			}

      		});

      		jButtonExcluir.setBorder(null);
      		jButtonExcluir.setBorderPainted(false);
      		jButtonExcluir.setContentAreaFilled(false);
      		jButtonExcluir.setCursor(new Cursor(HAND_CURSOR));
      		jButtonExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
      			public void mouseClicked(java.awt.event.MouseEvent evt) {
      				jButtonExcluirMouseClicked(evt);
      			}

      		});

      		jButtonVoltar.setBorder(null);
      		jButtonVoltar.setBorderPainted(false);
      		jButtonVoltar.setContentAreaFilled(false);
      		jButtonVoltar.setCursor(new Cursor(HAND_CURSOR));
      		jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
      			public void mouseClicked(java.awt.event.MouseEvent evt) {
      				jButtonVoltarMouseClicked(evt);
      			}

      		});

        jLabelHorarios.setBackground(new java.awt.Color(255, 255, 255));
        jLabelHorarios.setCursor(new Cursor(HAND_CURSOR));
        jLabelHorarios.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelHorarios.setForeground(new java.awt.Color(68, 114, 196));
        jLabelHorarios.setText("Informações detalhadas de horário.");
        jLabelHorarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHorariosMouseClicked(evt);
            }
        });

        jLabelDomingo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelDomingo.setForeground(new java.awt.Color(68, 114, 196));
        jLabelDomingo.setText("Domingo");
        jLabelDomingo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelSegunda.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelSegunda.setForeground(new java.awt.Color(68, 114, 196));
        jLabelSegunda.setText("Segunda");
        jLabelSegunda.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelTerça.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelTerça.setForeground(new java.awt.Color(68, 114, 196));
        jLabelTerça.setText("Terça");
        jLabelTerça.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelQuarta.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelQuarta.setForeground(new java.awt.Color(68, 114, 196));
        jLabelQuarta.setText("Quarta");
        jLabelQuarta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelQuinta.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelQuinta.setForeground(new java.awt.Color(68, 114, 196));
        jLabelQuinta.setText("Quinta");
        jLabelQuinta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelSexta.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelSexta.setForeground(new java.awt.Color(68, 114, 196));
        jLabelSexta.setText("Sexta");
        jLabelSexta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelSabado.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelSabado.setForeground(new java.awt.Color(68, 114, 196));
        jLabelSabado.setText("Sábado");
        jLabelSabado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelDomingoValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelDomingoValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelDomingoValue.setText(carByDay.get(0));
        jLabelDomingoValue.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelSegundaValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelSegundaValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelSegundaValue.setText(carByDay.get(1));
        jLabelSegundaValue.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelTercaValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelTercaValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelTercaValue.setText(carByDay.get(2));
        jLabelTercaValue.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelQuartaValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelQuartaValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelQuartaValue.setText(carByDay.get(3));
        jLabelQuartaValue.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelQuintaValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelQuintaValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelQuintaValue.setText(carByDay.get(4));
        jLabelQuintaValue.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelSextaValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelSextaValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelSextaValue.setText(carByDay.get(5));
        jLabelSextaValue.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelSabadoValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelSabadoValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelSabadoValue.setText(carByDay.get(6));
        jLabelSabadoValue.setHorizontalAlignment(SwingConstants.CENTER);

        jLabelTipo.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelTipo.setForeground(new java.awt.Color(68, 114, 196));
        jLabelTipo.setText("Tipo:");
        jLabelTipo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelTipoValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelTipoValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelTipoValue.setText(car.getTipo());
        jLabelTipoValue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelGaragem.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelGaragem.setForeground(new java.awt.Color(68, 114, 196));
        jLabelGaragem.setText("Garagem:");
        jLabelGaragem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelGaragemValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelGaragemValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelGaragemValue.setText(car.getGaragem());
        jLabelGaragemValue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelPlaca.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelPlaca.setForeground(new java.awt.Color(68, 114, 196));
        jLabelPlaca.setText("Placa:");
        jLabelPlaca.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelPlacaValue.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelPlacaValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelPlacaValue.setText(car.getPlaca());
        jLabelPlacaValue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelStatus.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(68, 114, 196));
        jLabelStatus.setText("Status");
        jLabelStatus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabelStatusValue.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabelStatusValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelStatusValue.setText(car.getStatus());
        jLabelStatusValue.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelPlacaValue, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelGaragem, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelGaragemValue, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabelTipoValue, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))))
                        .addGap(122, 122, 122)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDomingo, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSegunda, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTerça, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelQuarta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelQuinta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSexta, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSabado, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelStatusValue, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                                    .addComponent(jLabelDomingoValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelSegundaValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelTercaValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelQuartaValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelQuintaValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelSextaValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelSabadoValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabelHorarios, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelStatusValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDomingoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSegundaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelTercaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelQuartaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelQuintaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSextaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSabadoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelImagem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelDomingo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelSegunda, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelTipoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelTerça, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelGaragem, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelGaragemValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelQuarta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelPlacaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jLabelQuinta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSexta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelSabado, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabelHorarios, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>                        

   

    private void jButtonEditarMouseClicked(java.awt.event.MouseEvent evt) {                                           
       if(jButtonEditar.isEnabled()) {
    	new Tela_Carro_Editar().setVisible(true);
       setVisible(false);
       }
    }                                          

    private void jButtonExcluirMouseClicked(java.awt.event.MouseEvent evt) {                                            
       if(jButtonExcluir.isEnabled()) {
    	   Tela_Mensagem_Confirmacao.setRedirecionar("c");
           new Tela_Mensagem_Confirmacao().setVisible(true);
           setVisible(false);
       }
    }                                           

  

    private void jButtonVoltarMouseClicked(java.awt.event.MouseEvent evt) {                                           
        new Tela_Carro_Geral().setVisible(true);
        setVisible(false);
    }                                          

  

    private void jLabelHorariosMouseClicked(java.awt.event.MouseEvent evt) {                                            
       Tela_Carro_Horario.setIdCar(car.getNumero());
    	new Tela_Carro_Horario().setVisible(true);
        setVisible(false);
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Carro_Detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Carro_Detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Carro_Detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Carro_Detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

     

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Carro_Detalhes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelDomingo;
    private javax.swing.JLabel jLabelDomingoValue;
    private javax.swing.JLabel jLabelGaragem;
    private javax.swing.JLabel jLabelGaragemValue;
    private javax.swing.JLabel jLabelHorarios;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPlaca;
    private javax.swing.JLabel jLabelPlacaValue;
    private javax.swing.JLabel jLabelQuarta;
    private javax.swing.JLabel jLabelQuartaValue;
    private javax.swing.JLabel jLabelQuinta;
    private javax.swing.JLabel jLabelQuintaValue;
    private javax.swing.JLabel jLabelSabado;
    private javax.swing.JLabel jLabelSabadoValue;
    private javax.swing.JLabel jLabelSegunda;
    private javax.swing.JLabel jLabelSegundaValue;
    private javax.swing.JLabel jLabelSexta;
    private javax.swing.JLabel jLabelSextaValue;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelStatusValue;
    private javax.swing.JLabel jLabelTercaValue;
    private javax.swing.JLabel jLabelTerça;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JLabel jLabelTipoValue;
    // End of variables declaration                   
}
