package com.java.stagebus.view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;

import javax.swing.ImageIcon;

import com.java.stagebus.controller.GaragemController;
import com.java.stagebus.model.GaragemModel;
import com.java.stagebus.model.UsuarioModel;


/**
 *
 * @author User
 */
public class Tela_Garagem_Detalhes extends javax.swing.JFrame {
private static UsuarioModel userModel;
private static GaragemModel garage = new GaragemModel();
private GaragemController gc = new GaragemController();



    /**
     * Creates new form Tela_1
     */
    public Tela_Garagem_Detalhes() {
    	userModel = Tela_1.getDataUser();
    	garage = Tela_Garagem_Geral.getGarage();
        initComponents();
         getContentPane().setBackground(java.awt.Color.WHITE);
      
        setExtendedState(MAXIMIZED_BOTH);
        
        ImageIcon icon = new ImageIcon("src/main/resources/Images/imagem_garagem_default.png");
        Image image = icon.getImage().getScaledInstance(jLabelImagem.getWidth(), jLabelImagem.getHeight(), Image.SCALE_SMOOTH);
        jLabelImagem.setIcon(new ImageIcon(image));
        
       icon = new ImageIcon("src/main/resources/Images/btn_voltar.png");
        image = icon.getImage().getScaledInstance(jButtonVoltar.getWidth(), jButtonVoltar.getHeight(), Image.SCALE_SMOOTH);
        jButtonVoltar.setIcon(new ImageIcon(image));
        
        ImageIcon icon2;
       
     
        	
        
        
        if(userModel.isEd_gar()) {
        	icon = new ImageIcon("src/main/resources/Images/btn_editar.png");
        icon2 = new ImageIcon("src/main/resources/Images/btn_excluir.png");
        }
        else {
        	icon2 = new ImageIcon("src/main/resources/Images/btn_excluir_bloq.png");
        	 icon = new ImageIcon("src/main/resources/Images/btn_editar_bloq.png");
        	 jButtonEditar.setEnabled(false);
        	 jButtonExcluir.setEnabled(false);
        }
        
        image = icon.getImage().getScaledInstance(jButtonEditar.getWidth(), jButtonEditar.getHeight(), Image.SCALE_SMOOTH);
        jButtonEditar.setIcon(new ImageIcon(image));
        
        image = icon2.getImage().getScaledInstance(jButtonExcluir.getWidth(), jButtonExcluir.getHeight(), Image.SCALE_SMOOTH);
        jButtonExcluir.setIcon(new ImageIcon(image));

  
        
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jLabelLargura = new javax.swing.JLabel();
        jButtonEditar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabelImagem = new javax.swing.JLabel();
        jLabelComprimento = new javax.swing.JLabel();
        jLabelAltura = new javax.swing.JLabel();
        jLabelResponsavel = new javax.swing.JLabel();
        jLabelOnibus = new javax.swing.JLabel();
        jLabelLocalizacao = new javax.swing.JLabel();
        jLabelLarguraValue = new javax.swing.JLabel();
        jLabelComprimentoValue = new javax.swing.JLabel();
        jLabelAlturaValue = new javax.swing.JLabel();
        jLabelOnibusValue = new javax.swing.JLabel();
        jLabelResponsavelValue = new javax.swing.JLabel();
        jLabelLocalizacaoValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabelNome.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabelNome.setForeground(new java.awt.Color(127, 127, 127));
        jLabelNome.setText(garage.getNome());

        jLabelLargura.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelLargura.setForeground(new java.awt.Color(68, 114, 196));
        jLabelLargura.setText("Largura:");

        jButtonEditar.setBorder(null);
        jButtonEditar.setBackground(Color.WHITE);
        jButtonEditar.setBorderPainted(false);
        jButtonEditar.setContentAreaFilled(false);
        jButtonEditar.setCursor(new Cursor(HAND_CURSOR));
        jButtonEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditarMouseClicked(evt);
            }
          
        });
      

        jButtonExcluir.setBorder(null);
        jButtonExcluir.setBorderPainted(false);
        jButtonExcluir.setContentAreaFilled(false);
        jButtonExcluir.setCursor(new Cursor(HAND_CURSOR));
        jButtonExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonExcluirMouseClicked(evt);
            }
           
        });
        

        jButtonVoltar.setBorder(null);
        jButtonVoltar.setBorderPainted(false);
        jButtonVoltar.setContentAreaFilled(false);
        jButtonVoltar.setCursor(new Cursor(HAND_CURSOR));
        jButtonVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVoltarMouseClicked(evt);
            }
         
        });

        jLabelComprimento.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelComprimento.setForeground(new java.awt.Color(68, 114, 196));
        jLabelComprimento.setText("Comprimento:");

        jLabelAltura.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelAltura.setForeground(new java.awt.Color(68, 114, 196));
        jLabelAltura.setText("Altura:");

        jLabelResponsavel.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelResponsavel.setForeground(new java.awt.Color(68, 114, 196));
        jLabelResponsavel.setText("Responsável:");

        jLabelOnibus.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelOnibus.setForeground(new java.awt.Color(68, 114, 196));
        jLabelOnibus.setText("Ônibus vinculados:");

        jLabelLocalizacao.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelLocalizacao.setForeground(new java.awt.Color(68, 114, 196));
        jLabelLocalizacao.setText("Localização:");

        jLabelLarguraValue.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelLarguraValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelLarguraValue.setText(garage.getLargura()+"m");

        jLabelComprimentoValue.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelComprimentoValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelComprimentoValue.setText(garage.getComprimento()+"m");

        jLabelAlturaValue.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelAlturaValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelAlturaValue.setText(garage.getAltura()+"m");

        jLabelOnibusValue.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelOnibusValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelOnibusValue.setText(gc.amountBusOnGarage(garage.getId())+"");

        jLabelResponsavelValue.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelResponsavelValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelResponsavelValue.setText(garage.getResponsavel());

        jLabelLocalizacaoValue.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabelLocalizacaoValue.setForeground(new java.awt.Color(127, 127, 127));
        jLabelLocalizacaoValue.setText(garage.getLocal());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelLocalizacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelOnibus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                                    .addComponent(jLabelResponsavel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelAltura, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelComprimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelLargura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLarguraValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelComprimentoValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelAlturaValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelResponsavelValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelOnibusValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelLocalizacaoValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(100, 100, 100))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLargura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLarguraValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelComprimento, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelComprimentoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAlturaValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelResponsavelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOnibus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOnibusValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelLocalizacaoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabelImagem, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jButtonVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>                        

                         

    private void jButtonEditarMouseClicked(java.awt.event.MouseEvent evt) {                                           
        if(jButtonEditar.isEnabled()) {
        	new Tela_Garagem_Editar().setVisible(true);
        	setVisible(false);
        	
        }
    }                                          

    private void jButtonExcluirMouseClicked(java.awt.event.MouseEvent evt) {                                            
    	 if(jButtonExcluir.isEnabled()) {
      	   Tela_Mensagem_Confirmacao.setRedirecionar("g");
             new Tela_Mensagem_Confirmacao().setVisible(true);
             setVisible(false);
         }
    }                                           

   
    private void jButtonVoltarMouseClicked(java.awt.event.MouseEvent evt) {                                           
        new Tela_Garagem_Geral().setVisible(true);
        setVisible(false);
    }                                          
                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Garagem_Detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Garagem_Detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Garagem_Detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Garagem_Detalhes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Garagem_Detalhes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabelAltura;
    private javax.swing.JLabel jLabelAlturaValue;
    private javax.swing.JLabel jLabelComprimento;
    private javax.swing.JLabel jLabelComprimentoValue;
    private javax.swing.JLabel jLabelImagem;
    private javax.swing.JLabel jLabelLargura;
    private javax.swing.JLabel jLabelLarguraValue;
    private javax.swing.JLabel jLabelLocalizacao;
    private javax.swing.JLabel jLabelLocalizacaoValue;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelOnibus;
    private javax.swing.JLabel jLabelOnibusValue;
    private javax.swing.JLabel jLabelResponsavel;
    private javax.swing.JLabel jLabelResponsavelValue;
    // End of variables declaration                   
}

